# Generated by Django 4.1.4 on 2022-12-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_aadhar', models.CharField(max_length=100, null=True)),
                ('crime_type', models.CharField(max_length=100, null=True)),
                ('crime_desc', models.CharField(max_length=100, null=True)),
                ('crime_added_date', models.DateField(null=True)),
                ('aadhar_blk', models.CharField(max_length=100, null=True)),
                ('type_blk', models.CharField(max_length=100, null=True)),
                ('desc_blk', models.CharField(max_length=100, null=True)),
                ('date_blk', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'crime_details',
            },
        ),
        migrations.CreateModel(
            name='CriminalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criminal_aadhar', models.CharField(max_length=100, null=True)),
                ('criminal_name', models.CharField(max_length=100, null=True)),
                ('criminal_email', models.EmailField(max_length=100, null=True)),
                ('criminal_contact', models.CharField(max_length=100, null=True)),
                ('criminal_city', models.CharField(max_length=100, null=True)),
                ('criminal_profile', models.ImageField(null=True, upload_to='images/')),
                ('criminal_crime_date', models.DateField(null=True)),
                ('aadhar_block', models.CharField(max_length=100, null=True)),
                ('name_block', models.CharField(max_length=100, null=True)),
                ('email_block', models.CharField(max_length=100, null=True)),
                ('contact_block', models.CharField(max_length=100, null=True)),
                ('city_block', models.CharField(max_length=100, null=True)),
                ('profile_block', models.CharField(max_length=100, null=True)),
                ('date_block', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'criminals_details',
            },
        ),
        migrations.CreateModel(
            name='PoliceOfficerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_station', models.CharField(max_length=100, null=True)),
                ('officer_badgeno', models.CharField(max_length=100, null=True)),
                ('officer_name', models.CharField(max_length=100, null=True)),
                ('officer_email', models.EmailField(max_length=100, null=True)),
                ('officer_number', models.CharField(max_length=100, null=True)),
                ('officer_password', models.CharField(max_length=100, null=True)),
                ('officer_profile', models.ImageField(null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'police_officers_details',
            },
        ),
        migrations.CreateModel(
            name='PoliceStationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_state', models.CharField(max_length=100, null=True)),
                ('station_city', models.CharField(max_length=100, null=True)),
                ('station_name', models.CharField(max_length=100, null=True)),
                ('station_locality', models.CharField(max_length=100, null=True)),
                ('station_areacode', models.CharField(max_length=10, null=True)),
                ('station_contact', models.CharField(max_length=12, null=True)),
            ],
            options={
                'db_table': 'police_station_details',
            },
        ),
    ]
