# Generated by Django 4.1.4 on 2022-12-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_imgModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criminal_img', models.ImageField(null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'temp_images',
            },
        ),
    ]
